feat: implement LiteLLM for standardized LLM API calls for Embeddings
aietal/isaac pull request #37
Opened 2023-12-04 19:20 UTC by rishi-raj-jain

fix https://github.com/aietal/isaac/issues/28

2023-12-05 16:15 UTC, rishi-raj-jain commented
Would love to get this in and get onto the next one!

2023-12-07 08:04 UTC, rishi-raj-jain commented
Would love to get this in and get onto the next one!

2023-12-07 08:08 UTC, rishi-raj-jain commented on web/utils/create_embedding.ts
> +    const embedding = await fetch('http://0.0.0.0:5001/api/embedding', {
The same as done in the last PR

2023-12-10 15:11 UTC, eimenhmdt requested changes
Code lgtm. Would be great, however, if you could replace the hardcoded host and api key in create_embedding.ts with the following env vars:

api host: process.env.NEXT_PUBLIC_API_HOST
api key: process.env.NEXT_PUBLIC_API_ROUTE_SECRET 

Thanks!

2023-12-10 15:25 UTC, eimenhmdt approved these changes
Thanks for the modifications. Approved!

2023-12-10 15:25 UTC, merged