feat: added compose and Dockerfile for web
aietal/isaac pull request #60
Opened 2024-01-09 14:04 UTC by ezhil56x

## Description
- Added `docker-compose.yml` which can be used to start and stop the containers
- Environment variables which start with `NEXT` are required at build time so that should be added in `web/Dockerfile`
- `web` container uses the `web/.env.example`, remaining variables can be added in `.env.example`

2024-01-09 15:26 UTC, ologbonowiwi requested changes
IMO we need also an update on supabase guide (following the example from capgo on the issue) and preferably a service on docket-compose.yml that runs supabase

2024-01-09 16:01 UTC, ezhil56x commented
> IMO we need also an update on supabase guide (following the example from capgo on the issue) and preferably a service on docket-compose.yml that runs supabase

Will add a commit asap

2024-01-09 16:53 UTC, ologbonowiwi commented
> Will add a commit asap

thank you! if possible (I don't know if it is), run also the necessary migrations, so the users will not have to run it by themselves

2024-01-09 17:02 UTC, eimenhmdt commented
agree with @ologbonowiwi

2024-01-09 19:18 UTC, ezhil56x commented
@ologbonowiwi @eimenhmdt Required changes have been done. Can you review once?

2024-01-09 19:33 UTC, ologbonowiwi commented on README.md
> +supabase start
I recommend to set examples using `npx supabase` so the users does not need to install it globally

2024-01-09 19:44 UTC, ezhil56x commented on README.md
> +supabase start
Done 👍🏻

2024-01-09 20:08 UTC, ologbonowiwi commented on README.md
> +## Installation Steps (Docker)
as we're not using Docker for this, we can remove it
```suggestion
## Installation Steps
```

2024-01-09 20:09 UTC, ologbonowiwi commented on README.md
> +## Installation Steps (Docker)
ohh I see there are stuff related to the repo and docker also. maybe should we split then? do one part only to set up supabase

2024-01-09 20:09 UTC, ologbonowiwi commented on README.md
> +## Installation Steps (Docker)
actually, you can leave as it is

2024-01-09 20:09 UTC, ologbonowiwi approved these changes
LGTM

2024-01-09 22:30 UTC, eimenhmdt commented on README.md
Change to: "Installation using Docker (Recommended)

2024-01-09 22:30 UTC, eimenhmdt commented on README.md
> +1. Install Supabase CLI from [here](https://supabase.com/docs/guides/cli/getting-started)
"Install the Supabase CLI following the instructions here"

2024-01-09 22:31 UTC, eimenhmdt commented on README.md
> +7. Add the other required environment variables to `api/app/.env.example`, `web/.env.example` and `web/Dockerfile`
Why to .env.example? The idea is to replace the .env.example files with actual .env files containing the environment vars.

2024-01-09 22:50 UTC, eimenhmdt requested changes

2024-01-09 22:50 UTC, eimenhmdt commented on README.md
> +create extension vector with schema extensions;
Change to: 

`create extension vector with schema public;`

2024-01-09 22:50 UTC, eimenhmdt commented on api/app/.env.example
move this to from api/app to api/

2024-01-10 01:40 UTC, ezhil56x commented on api/app/.env.example
Done 👍🏻

2024-01-10 01:41 UTC, ezhil56x commented on README.md
> +7. Add the other required environment variables to `api/app/.env.example`, `web/.env.example` and `web/Dockerfile`
`.env` is ignored by `.gitignore`. If required we can add another point to copy to `.env`

2024-01-10 01:42 UTC, ezhil56x commented on README.md
> +1. Install Supabase CLI from [here](https://supabase.com/docs/guides/cli/getting-started)
Done 👍🏻

2024-01-10 01:42 UTC, ezhil56x commented on README.md
Done 👍🏻

2024-01-10 01:43 UTC, ezhil56x commented on README.md
> +create extension vector with schema extensions;
This doesn't seem to work I have already tried, throws error

```
ERROR: type "extensions.vector" does not exist (SQLSTATE 42704)
At statement 12: create table document_embeddings (            
  id bigint not null primary key,                              
  content text,                                                
  metadata jsonb,                                              
  embedding extensions.vector(1536),                           
  upload_id uuid references uploads (id),                      
  searchable_content tsvector,                                 
  updated_at timestamp default now()                           
) 
```

2024-01-10 14:45 UTC, ezhil56x commented
@eimenhmdt Any update or changes required?

2024-01-10 18:41 UTC, eimenhmdt approved these changes

2024-01-10 22:08 UTC, merged

2024-01-15 09:54 UTC, rishi-raj-jain commented
```
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public."profile" (id, email, has_seen_community_banner, editor_language)
  values (new.id, new.email, false, "English");
  return new;
end;
$$
language plpgsql
security definer
set search_path = public
;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
```

fails to work