Fix: Preserve column casing of documents.projectId
aietal/isaac pull request #85
Opened 2024-01-27 17:03 UTC by ShaneMaglangit

Preserve column casing of documents.projectId (similar to https://github.com/aietal/isaac/pull/80)

2024-01-27 17:49 UTC, ShaneMaglangit commented on web/hooks/api/useInitializeUserUploads.tsx
> +			void supabase.removeChannel(subscription);
Not sure if this is the correct v2 version of this but won't bother fixing:
- Deprecated function
- No existing usage (safe to remove, unless we have a specific reason for keeping it)

2024-01-27 18:28 UTC, eimenhmdt requested changes
Thanks for the PR!

The code looks good in general and everything seems to function as intended. However, I came across a small bug: When clicking sign out, the landing page only updates after refreshing and then renders the correct state.

![CleanShot 2024-01-27 at 19 23 24](https://github.com/aietal/isaac/assets/64800243/3245ab84-c403-4fa7-ab3b-9f99cc11f14e)

2024-01-27 18:29 UTC, eimenhmdt commented
Thank you for the contribution. I reviewed the code. Also, I fully agree with the need to implement proper testing.

2024-01-28 02:36 UTC, ShaneMaglangit commented
> Thanks for the PR!
> 
> The code looks good in general and everything seems to function as intended. However, I came across a small bug: When clicking sign out, the landing page only updates after refreshing and then renders the correct state.
> 
> ![CleanShot 2024-01-27 at 19 23 24](https://private-user-images.githubusercontent.com/64800243/300199743-3245ab84-c403-4fa7-ab3b-9f99cc11f14e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MDc5MTgsIm5iZiI6MTcwNjQwNzYxOCwicGF0aCI6Ii82NDgwMDI0My8zMDAxOTk3NDMtMzI0NWFiODQtYzQwMy00ZmE3LWFiM2ItOWY5OWNjMTFmMTRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAyMDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MDBiYmQ1YWVhYTRhMjQwYjczOWRjYjRjYmI3MzlkMWQzZTYxOGU0YjEyZWUzMTlkM2Y5ZDg3MTEyM2IyOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3FMH7HfBjaFYLfl1I3-wnnIGzLFAlAqDBEkXtvzhIVw) [ ![CleanShot 2024-01-27 at 19 23 24](https://private-user-images.githubusercontent.com/64800243/300199743-3245ab84-c403-4fa7-ab3b-9f99cc11f14e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MDc5MTgsIm5iZiI6MTcwNjQwNzYxOCwicGF0aCI6Ii82NDgwMDI0My8zMDAxOTk3NDMtMzI0NWFiODQtYzQwMy00ZmE3LWFiM2ItOWY5OWNjMTFmMTRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAyMDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MDBiYmQ1YWVhYTRhMjQwYjczOWRjYjRjYmI3MzlkMWQzZTYxOGU0YjEyZWUzMTlkM2Y5ZDg3MTEyM2IyOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3FMH7HfBjaFYLfl1I3-wnnIGzLFAlAqDBEkXtvzhIVw) ](https://private-user-images.githubusercontent.com/64800243/300199743-3245ab84-c403-4fa7-ab3b-9f99cc11f14e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MDc5MTgsIm5iZiI6MTcwNjQwNzYxOCwicGF0aCI6Ii82NDgwMDI0My8zMDAxOTk3NDMtMzI0NWFiODQtYzQwMy00ZmE3LWFiM2ItOWY5OWNjMTFmMTRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAyMDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MDBiYmQ1YWVhYTRhMjQwYjczOWRjYjRjYmI3MzlkMWQzZTYxOGU0YjEyZWUzMTlkM2Y5ZDg3MTEyM2IyOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3FMH7HfBjaFYLfl1I3-wnnIGzLFAlAqDBEkXtvzhIVw) [ ](https://private-user-images.githubusercontent.com/64800243/300199743-3245ab84-c403-4fa7-ab3b-9f99cc11f14e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MDc5MTgsIm5iZiI6MTcwNjQwNzYxOCwicGF0aCI6Ii82NDgwMDI0My8zMDAxOTk3NDMtMzI0NWFiODQtYzQwMy00ZmE3LWFiM2ItOWY5OWNjMTFmMTRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAyMDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MDBiYmQ1YWVhYTRhMjQwYjczOWRjYjRjYmI3MzlkMWQzZTYxOGU0YjEyZWUzMTlkM2Y5ZDg3MTEyM2IyOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3FMH7HfBjaFYLfl1I3-wnnIGzLFAlAqDBEkXtvzhIVw)

Great catch! I've pushed a commit to fix this. Will appreciate if you can have another look @eimenhmdt :boomerang:

2024-01-28 06:51 UTC, eimenhmdt approved these changes
lgtm now

2024-01-28 06:52 UTC, merged

2024-01-28 07:03 UTC, eimenhmdt commented
@ShaneMaglangit I'm getting a build error when trying to deploy the merged code:

`
Type error: Property 'weak_password' does not exist on type '{ user: User; session: Session; weak_password?: WeakPassword; } \| { user: null; session: null; }'.
--
08:02:16.170 | Property 'weak_password' does not exist on type '{ user: null; session: null; }'.
08:02:16.170 |  
08:02:16.170 | 189 \|     data.weak_password.reasons.reduce((a: boolean, i: any) => a && typeof i === 'string', true)
08:02:16.170 | 190 \|   ) {
08:02:16.170 | > 191 \|     response.data.weak_password = data.weak_password
08:02:16.170 | \|                   ^
08:02:16.170 | 192 \|   }
08:02:16.170 | 193 \|
08:02:16.170 | 194 \|   return response
08:02:16.297 | Error: Command "npm run build" exited with 1
`

Do you have any idea what causes this?

2024-01-28 07:07 UTC, ShaneMaglangit commented
> I'm getting a build error when trying to deploy the merged code:
@eimenhmdt hmm let me check

2024-01-28 07:11 UTC, ShaneMaglangit commented
@eimenhmdt what file/line is this? can't find anything with grep.